name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Setup .NET Core"
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: "3.1"
      - 
        name: "Build with dotnet"
        run: "dotnet build --configuration Release .\\testCICD"
      - 
        name: "dotnet publish"
        run: "dotnet publish -c Release -o TestCICD .\\testCICD\n"
      - 
        name: "Deploy to IIS"
        run: |
            iisreset /stop
            Copy-Item ./testCIId/* C:/inetpub/wwwroot/dotnetcore-webapp -Recurse -Force
            iisreset /start
      - 
        name: "Curl the website as a smoke test"
        run: "curl http://localhost/dotnetcore-webapp"
