name: .NET

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1
      - run: dotnet build 
      - name: upload content
        uses: actions/upload-artifact@v2
        with:
          name: uploadartifact
          path: pathtt
  deploy:
     name: release
     runs-on: ubuntu-latest
     needs: build
     steps:
     - name: donwloadartifact
       uses: actions/download-artifact@v3
       with:
        path: tt
     - name:  testDonwload
       run : ls -R
