name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy to IIS
      uses: actions/upload-artifact@v1
      with:
         name: my-artifact
         path: path/to/artifact/ 
  release-project:
     name: release
     runs-on: ubunto-latest
     steps:
     - name: donwloadartifact
       uses: actions/upload-artifact@v1
       with:
        name: testArtifact
     - name:  testDonwload
       run : ls -R
