name: .NET

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: upload content
      uses: actions/upload-artifact@v3
      with:
        name: donwloadartifact
        path: tt
  release-project:
     name: release
     runs-on: ubuntu-latest
     needs: build
     steps:
     - name: donwloadartifact
       uses: actions/download-artifact@v3
       with:
        path: tt
     - name:  testDonwload
       run : ls -R
